name: independent_localization
author: Ye Htet Hein
description: Localization package that does not depend on flutter's localization.
version: 0.0.1
homepage: https://www.facebook.com/Ch405.yhh/

environment:
  sdk: '>=2.12.0 <3.0.0'
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  devicelocale: ^0.4.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

